// packages/md-parser-react/src/components/Hashtag.tsx
export interface HashtagProps {
  /** 标签名 */
  tag: string;
  /** 点击回调 */
  onClick?: (tag: string) => void;
}

/**
 * #标签组件
 */
export function Hashtag({ tag, onClick }: HashtagProps) {
  const handleClick = () => {
    onClick?.(tag);
  };

  return (
    <a
      href={`/tag/${tag}`}
      className="hashtag"
      data-tag={tag}
      onClick={(e) => {
        if (onClick) {
          e.preventDefault();
          handleClick();
        }
      }}
    >
      #{tag}
    </a>
  );
}

// packages/md-parser-vue/src/components/Hashtag.vue
<template>
  <a
    :href="`/tag/${tag}`"
    class="hashtag"
    :data-tag="tag"
    @click="handleClick"
  >
    #{{ tag }}
  </a>
</template>

<script setup lang="ts">
interface Props {
  /** 标签名 */
  tag: string;
}

interface Emits {
  /** 点击回调 */
  (e: 'click', tag: string): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const handleClick = (e: Event) => {
  e.preventDefault();
  emit('click', props.tag);
};
</script>
