// packages/md-parser-react/src/components/Mention.tsx
export interface MentionProps {
  /** 用户名 */
  username: string;
  /** 点击回调 */
  onClick?: (username: string) => void;
}

/**
 * @用户提及组件
 */
export function Mention({ username, onClick }: MentionProps) {
  const handleClick = () => {
    onClick?.(username);
  };

  return (
    <a
      href={`/user/${username}`}
      className="mention"
      data-username={username}
      onClick={(e) => {
        if (onClick) {
          e.preventDefault();
          handleClick();
        }
      }}
    >
      @{username}
    </a>
  );
}

// packages/md-parser-vue/src/components/Mention.vue
<template>
  <a
    :href="`/user/${username}`"
    class="mention"
    :data-username="username"
    @click="handleClick"
  >
    @{{ username }}
  </a>
</template>

<script setup lang="ts">
interface Props {
  /** 用户名 */
  username: string;
}

interface Emits {
  /** 点击回调 */
  (e: 'click', username: string): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const handleClick = (e: Event) => {
  e.preventDefault();
  emit('click', props.username);
};
</script>
